### ISSUE TITLE
How to use code block with dark background

### ISSUE THREAD

**Issue by FeynmanZhou** [once-ui-system/nextjs-starter#1]
Hi team,

I am using OnceUI to build my personal portfolio website. I didn't see any components of code block on the docs https://once-ui.com/docs/accordion.

How can I use code block with dark background?

Thanks

**Comment by lorant-one** [comment]
@FeynmanZhou the CodeBlock component will be included in our next release (coming in a few weeks). until then, [join our discord](https://discord.com/invite/5EyAQ4eNdS) and i'll share the release candidate with you (theme adapts to your settings like any other component in the system).

**Comment by FeynmanZhou** [comment]
Great! I look forward to the new version. Just joined the Discord. @lorant-one

**Comment by lorant-one** [comment]
@FeynmanZhou the CodeBlock is now available in the 0.4 version! you can view the demo in the [docs](https://once-ui.com/docs/codeBlock)
