### ISSUE TITLE
 Left Menu Overlapping Content on Medium Screens (About Page)

### ISSUE THREAD

**Issue by Aymen-drid** [once-ui-system/nextjs-starter#14]
**Tell us what happened**
On medium-sized screens, the left menu overlaps the main content, making it difficult to view or interact with the underlying items.

**Affected components**
The left menu and the main content layout.

**How do we reproduce it?**

1-Open the website on a medium screen (e.g., 768px - 1024px width).
2-Navigate to a page with the left menu visible.
3-Observe how the left menu overlaps the main content instead of properly resizing or staying aligned.

**Screenshots**
![Screenshot_2024-11-18_19_27_06](https://github.com/user-attachments/assets/07e71981-cbb7-4053-9161-be3d840716da)

**Comment by lorant-one** [comment]
thanks for reporting @Aymen-drid, it's related to the magic portfolio repo and we have [another issue](https://github.com/once-ui-system/magic-portfolio/issues/12) reported already, so i'm closing this one
