### ISSUE TITLE
Can you provide the source code of the document?

### ISSUE THREAD

**Issue by everfu** [once-ui-system/nextjs-starter#24]
I love your UI and I want to use it as my documentation, but I don't want to start from scratch.

**Comment by zsofiakm** [comment]
Hey @everfu,
Thank you for sponsoring the project. As @lorant-one mentioned on Discord, we are planning to release the documentation template in February as part of the Once UI Pro plan. 

Until then what I could recommend is using the existing components like Header, Sidebar, CodeBlock etc. from this starter. (Table is also coming soon.)

**Comment by everfu** [comment]
👌
